### ISSUE TITLE
Add other unit tests

### ISSUE THREAD

**Issue by Shyam-Chen** [Puigcerber/angular-unit-testing#1]
There are plans to add the Factory, Decorator, Filter, Component Router and Animation unit tests do?

**Comment by Puigcerber** [comment]
Hi @Shyam-Chen! I don't have plans right now as this was more about common patterns that I've encountered while testing AngularJS apps. 

You can test factories the same way you test services. Filters are really easy to test, for a given input you test for the expected output. I have to say I never used the decorator method neither animations. And the component router only with Angular 2.

Cheers, Pablo.
