### ISSUE TITLE
$componentController vs. $compile

### ISSUE THREAD

**Issue by benjyblack** [Puigcerber/angular-unit-testing#2]
This is more of a question than anything else, but in your component spec examples you provide a couple different ways of testing. One is the traditional directive testing done with `$compile`. The other is using `$componentController`.

The angular docs recommend using `$componentController` but `$compile` seems so much more powerful. You provide examples of both, but could you provide some insight as to why anyone would want to use `$componentController` over `$compile`? What do you use in your own testing?

**Comment by Puigcerber** [comment]
Hi @benjyblack! 

That's actually a good question and I guess I should update the guide. I actually wrote a blog post about [how to test components](https://puigcerber.com/2016/02/07/how-to-test-angular-1-5-components/) last year. 

I'm used to `$compile` testing both the compiled element and the controller, but if you don't need or want to test the compiled element you can just use `$componentController`. I think it also depends on your testing strategy, you could use `$componentController` for testing the logic of your components and E2E Testing for the compiled part and how they interact with each other.

Let me know if it helps!

**Comment by benjyblack** [comment]
Thanks for the answer @Puigcerber! After trying out some testing with `$compile` I think I've actually come to the conclusion that I would prefer to use `$componentController`. Testing the template is a _lot_ of overhead and Jasmine/JQlite don't lend themselves particularly well to the job.

I like your suggestion of unit testing via `$componentController` and E2E testing the compiled components and their interaction with other parts of the app. Thanks for the clarification :)

BTW I also [asked this question](https://stackoverflow.com/questions/44164742/compile-vs-componentcontroller) on StackOverflow. The answers there seem to be in line with yours.
