### ISSUE TITLE
Error when executing npm test

### ISSUE THREAD

**Issue by chupee120** [Puigcerber/angular-unit-testing#3]
Hello,

Please could you help?

> angular-unit-testing@1.0.0 test /Users/Kong/Dev/angularjs/angular-unit-testing/example
> karma start --singleRun

/Users/Joe/Dev/angularjs/angular-unit-testing/example/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/Kong/Dev/angularjs/angular-unit-testing/example/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)

**Comment by Puigcerber** [comment]
Hi @chupee120! 

There isn't much I can do without having a look into your codebase and just by looking at your errors. But it's related to the way you use Socket.io as you might have to mock it in your tests.

Cheers, Pablo.
